spring.application.name=CBS
twilio.account.sid=AC14a29ae7c5e8ee1c9088e184838fb9f9
twilio.auth.token=7bb243aefc48135cdb8a828215bf3d07
twilio.phone.number=+14634652148
spring.jpa.hibernate.ddl-auto=update