CREATE TABLE TB_OTP_SESSION (
    SESSION_ID VARCHAR(255) PRIMARY KEY,
    USER_ID VARCHAR(255),
    USERNAME VARCHAR(255),
    CREATED_AT TIMESTAMP,
    EXPIRES_AT TIMESTAMP
);

select * from TB_OTP_SESSION;

	
select * from tb_user_master;

SELECT * from TB_OTP;
DELETE FROM TB_OTP_SESSION;