INSERT INTO TB_ONBOARDING_STAGE_MASTER 
(stage_code, stage_name, stage_order, is_active)
VALUES 
('BASIC_INFO','Basic Information',1,true),
('ADDRESS_INFO','Address Information',2,true),
('DOCUMENT_UPLOAD','Document Upload',3,true),
('KYC_VERIFIED','KYC Verified',4,true),
('COMPLETED','Completed',5,true);

SELECT * FROM TB_ONBOARDING_STAGE_MASTER;

SELECT cif_id, onboarding_stage
FROM tb_cif_master
WHERE cif_id = 'CIF1002';

UPDATE TB_CIF_MASTER
SET first_name = 'Parmeshwar',
    last_name = 'Bodake',
    mobile_no = '9876543210',
    email = 'test@mail.com',
    onboarding_stage = 'ADDRESS',
    updated_at = CURRENT_TIMESTAMP
WHERE cif_id = 'CIF1002'
AND cif_status = 'DRAFT';


CREATE TABLE TB_CIF_ADDRESS (
    ADDRESS_ID      VARCHAR(20) PRIMARY KEY,
    CIF_ID          VARCHAR(20) NOT NULL,
    ADDRESS_TYPE    VARCHAR(20) NOT NULL,
    ADDRESS_LINE1   VARCHAR(200) NOT NULL,
    ADDRESS_LINE2   VARCHAR(200),
    CITY            VARCHAR(100) NOT NULL,
    STATE           VARCHAR(100) NOT NULL,
    POSTAL_CODE     VARCHAR(10) NOT NULL,
    COUNTRY         VARCHAR(50) NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_ADDRESS_CIF
        FOREIGN KEY (CIF_ID)
        REFERENCES TB_CIF_MASTER(CIF_ID)
);

CREATE TABLE TB_KYC_DETAILS (
    KYC_ID              VARCHAR(20) PRIMARY KEY,
    CIF_ID              VARCHAR(20) NOT NULL,
    PAN_NUMBER          VARCHAR(20),
    AADHAAR_NUMBER      VARCHAR(20),
    KYC_TYPE            VARCHAR(20),
    VERIFICATION_STATUS VARCHAR(20) DEFAULT 'PENDING',
    VERIFIED_BY         VARCHAR(20),
    VERIFIED_DATE       TIMESTAMP,

    CONSTRAINT FK_KYC_CIF
        FOREIGN KEY (CIF_ID)
        REFERENCES TB_CIF_MASTER(CIF_ID)
);


CREATE TABLE TB_DOCUMENTS (
    DOC_ID          VARCHAR(20) PRIMARY KEY,
    CIF_ID          VARCHAR(20) NOT NULL,
    DOC_TYPE        VARCHAR(50) NOT NULL,
    FILE_PATH       VARCHAR(500),
    UPLOADED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPLOADED_BY     VARCHAR(20),

    CONSTRAINT FK_DOC_CIF
        FOREIGN KEY (CIF_ID)
        REFERENCES TB_CIF_MASTER(CIF_ID)
);

CREATE TABLE TB_RISK_PROFILE (
    RISK_ID                     VARCHAR(20) PRIMARY KEY,
    CIF_ID                      VARCHAR(20) NOT NULL,
    INCOME_RANGE                VARCHAR(50),
    OCCUPATION                  VARCHAR(100),
    COUNTRY_OF_RESIDENCE        VARCHAR(100),
    POLITICALLY_EXPOSED_PERSON  BOOLEAN DEFAULT FALSE,
    RISK_CATEGORY               VARCHAR(20),
    ASSESSED_BY                 VARCHAR(20),
    ASSESSED_DATE               TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_RISK_CIF
        FOREIGN KEY (CIF_ID)
        REFERENCES TB_CIF_MASTER(CIF_ID)
);

CREATE SEQUENCE SEQ_ADDRESS START 1001;
CREATE SEQUENCE SEQ_KYC START 2001;
CREATE SEQUENCE SEQ_DOC START 3001;
CREATE SEQUENCE SEQ_RISK START 4001;

CREATE OR REPLACE FUNCTION FN_GENERATE_ADDRESS()
RETURNS VARCHAR AS $$
BEGIN
    RETURN 'ADDR' || nextval('SEQ_ADDRESS');
END;
$$ LANGUAGE plpgsql;


SELECT onboarding_stage
FROM TB_CIF_MASTER
WHERE cif_id='CIF1002';

SELECT cif_status
FROM TB_CIF_MASTER
WHERE cif_id='CIF1002';
SELECT * FROM TB_RISK_PROFILE;
SELECT * FROM TB_CIF_MASTER;
SELECT * FROM TB_KYC_DETAILS;
SELECT * FROM TB_CIF_ADDRESS;